
name: Build DEV version

on:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      docker_tag:
        description: "Docker Tag Prefix (leave blank for no docker build)"
        required: false

jobs:
  prinfo:
    name: "Get PR info"
    runs-on: ubuntu-latest
    outputs:
      build_docker: ${{ steps.loadinfo.outputs.build_docker }}
      docker_tag: ${{ steps.loadinfo.outputs.docker_tag }}
    steps:
    - name: "Load PR info"
      id: loadinfo
      run: |
        has_docker_image_label="${{ contains(github.event.pull_request.labels.*.name, 'build-docker-image') }}"
        echo "docker image label: $has_docker_image_label"

        branch_name="${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
        echo "branch name: $branch_name"
        
        manual_tag="${{ inputs.docker_tag }}"
        if [[ ! -z "$manual_tag" ]]; then
          has_docker_image_label="true"
          branch_name="$manual_tag"
        fi

        echo "build_docker=$has_docker_image_label" >> $GITHUB_OUTPUT
        echo "docker_tag=$branch_name" >> $GITHUB_OUTPUT

  check_source:
    name: "Run code checks"
    uses: ./.github/workflows/_shared-check.yaml

  build_binaries:
    name: "Build Dora"
    needs: [prinfo, check_source]
    uses: ./.github/workflows/_shared-build.yaml
    with:
      docker: ${{ needs.prinfo.outputs.build_docker == 'true' }}
      repository: "ethpandaops/dora"
      tag: ${{needs.prinfo.outputs.docker_tag}}
      additional_tags: "['${{needs.prinfo.outputs.docker_tag}}','${{needs.prinfo.outputs.docker_tag}}-latest']"
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
