
name: Build DEV version

on:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:

  build_binaries:
    name: Build Binaries
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # setup global dependencies
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.x

    # setup project dependencies
    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    # build binaries
    - run: |
        make build

    # upload artifacts
    - name: "Upload artifact: explorer_windows_amd64.exe"
      uses: actions/upload-artifact@v3
      with:
        path: ./bin/explorer_windows_amd64.exe
        name: explorer_windows_amd64.exe
    - name: "Upload artifact: explorer_linux_amd64"
      uses: actions/upload-artifact@v3
      with:
        path: ./bin/explorer_linux_amd64
        name: explorer_linux_amd64
    - name: "Upload artifact: explorer_darwin_amd64"
      uses: actions/upload-artifact@v3
      with:
        path: ./bin/explorer_darwin_amd64
        name: explorer_darwin_amd64

